# Generated by Django 3.1 on 2020-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.IntegerField(default=''),
        ),
    ]
